### ISSUE TITLE
tables_demo.py: dictionary changed size during iteration

### ISSUE THREAD

**Issue by mintar** [DFKI-NI/mobipick_labs#44] opened 2024-02-27 10:17 UTC
As discussed in the meeting today, the error below happened every time both on the real Mobipick robot and on my laptop. Never happened on @sebastianstock's laptop or on `mobipick_labs_docker`. When trying to reproduce a day later on my laptop, it never occurred.

```text
$ rosrun tables_demo_planning tables_demo_node.py
[INFO] [1708609835.663552, 104.718000]: waiting for pose selector services: /pick_pose_selector_node/pose_selector_activate, /pick_pose_selector_node/pose_selector_class_query, /pick_pose_selector_node/pose_selector_get_all, /pick_pose_selector_node/pose_selector_clear (/robot_api_69941)
[INFO] [1708609835.668844, 104.733000]: found pose selector services (/robot_api_69941)
Using /mobipick/pick_object_node/planning_scene_boxes parameter.
Scenario: Mobipick shall bring a KLT with a multimeter inside to table_2.
The believed item locations are:
- multimeter_1: anywhere
- klt_1: anywhere
- klt_2: anywhere
- klt_3: anywhere
Traceback (most recent call last):
  File "/home/mguenther/ros/noetic/mobipick/devel/lib/tables_demo_planning/tables_demo_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mguenther/ros/noetic/mobipick/src/mobipick_labs/tables_demo_planning/nodes/tables_demo_node.py", line 70, in <module>
    api.run(target_location)
  File "/home/mguenther/ros/noetic/mobipick/src/mobipick_labs/tables_demo_planning/src/tables_demo_planning/tables_demo_api.py", line 119, in run
    plan = self.replan()
  File "/home/mguenther/ros/noetic/mobipick/src/mobipick_labs/tables_demo_planning/src/tables_demo_planning/tables_demo_api.py", line 108, in replan
    self.domain.set_initial_values(self.problem)
  File "/home/mguenther/ros/noetic/mobipick/src/embedded-systems-bridge/up_esb/bridge.py", line 362, in set_initial_values
    else self._fluent_functions[fluent.name](*parameters)
  File "/home/mguenther/ros/noetic/mobipick/src/mobipick_labs/tables_demo_planning/src/tables_demo_planning/tables_demo.py", line 127, in get_pose_at
    self.initialize_pose_locations()
  File "/home/mguenther/ros/noetic/mobipick/src/mobipick_labs/tables_demo_planning/src/tables_demo_planning/tables_demo.py", line 117, in initialize_pose_locations
    for name, obj in self.objects.items():
RuntimeError: dictionary changed size during iteration
```

The issue seems is caused by the fact that `self.get` can modify `self.objects` while iterating over it:

https://github.com/DFKI-NI/mobipick_labs/blob/ebc06d97520c94b594ee5aa49eeff223c6bf9cc6/tables_demo_planning/src/tables_demo_planning/tables_demo.py#L115-L122

It's still a bit of a mystery why it consistently happened on some setups and not on others.

The workaround for now is that @alexander-sung will create all objects explicitly beforehand, so `objects` doesn't change dynamically.

**Comment by mintar** [comment] 2024-02-27 15:40
**UPDATE:** I finally figured out how to reproduce this - it is not a race condition after all!

To reproduce the bug, you have to add the `world_config:=cic_tables` argument to your launch file calls like so:

### real mobipick

```text
roslaunch mobipick_bringup mobipick_bringup_both.launch
roslaunch pbr_dope dope.launch
roslaunch tables_demo_bringup bringup.launch world_config:=cic_tables
rosrun tables_demo_planning tables_demo_node.py
```

### Gazebo

```text
roslaunch tables_demo_bringup demo_sim.launch world_config:=cic_tables world:=pbr_cic robot_x:=20.50 robot_y:=15.20
rosrun tables_demo_planning tables_demo_node.py
```

This will cause the [cic_tables_demo.yaml](https://github.com/DFKI-NI/mobipick/blob/a718c50a5189e44c28e7438ea6ff6b172de4d802/mobipick_pick_n_place/config/cic_tables_demo.yaml) file to be loaded instead of the default of [moelk_tables_demo.yaml](https://github.com/DFKI-NI/mobipick/blob/a718c50a5189e44c28e7438ea6ff6b172de4d802/mobipick_pick_n_place/config/moelk_tables_demo.yaml).

The `cic_tables_demo.yaml` file has an additional table 4, and sure enough, that's the problem! If we print `self.objects` before and after the exception is thrown, the only difference is that the state afterwards has an additional `('table_4', table_4)` entry:

```python
# BEFORE
self.objects == dict_items([('mobipick', mobipick), ('unknown', unknown), ('nothing', nothing), ('anywhere', anywhere), ('base_handover_pose', base_handover_pose), ('base_home_pose', base_home_pose), ('base_table_1_pose', base_table_1_pose), ('base_table_2_pose', base_table_2_pose), ('base_table_3_pose', base_table_3_pose), ('base_table_4_pose', base_table_4_pose), ('unknown_pose', unknown_pose), ('tool_search_pose', tool_search_pose), ('klt_search_pose', klt_search_pose), ('multimeter_1', multimeter_1), ('klt_1', klt_1), ('klt_2', klt_2), ('klt_3', klt_3), ('table_1', table_1), ('table_2', table_2), ('table_3', table_3), ('home', home), ('transport', transport), ('tool_search_location', tool_search_location), ('klt_search_location', klt_search_location), ('on_robot', on_robot), ('arm_pose_home', arm_pose_home), ('in_klt', in_klt), ('handover', handover), ('observe100cm_right', observe100cm_right)])

# AFTER
self.objects == dict_items([('mobipick', mobipick), ('unknown', unknown), ('nothing', nothing), ('anywhere', anywhere), ('base_handover_pose', base_handover_pose), ('base_home_pose', base_home_pose), ('base_table_1_pose', base_table_1_pose), ('base_table_2_pose', base_table_2_pose), ('base_table_3_pose', base_table_3_pose), ('base_table_4_pose', base_table_4_pose), ('unknown_pose', unknown_pose), ('tool_search_pose', tool_search_pose), ('klt_search_pose', klt_search_pose), ('multimeter_1', multimeter_1), ('klt_1', klt_1), ('klt_2', klt_2), ('klt_3', klt_3), ('table_1', table_1), ('table_2', table_2), ('table_3', table_3), ('home', home), ('transport', transport), ('tool_search_location', tool_search_location), ('klt_search_location', klt_search_location), ('on_robot', on_robot), ('arm_pose_home', arm_pose_home), ('in_klt', in_klt), ('handover', handover), ('observe100cm_right', observe100cm_right), ('table_4', table_4)])
```

**Comment by alexander-sung** [comment] 2024-02-27 15:49
I'm glad, it's just in time since I was going to investigate as well why this could lead to a reproducible error which doesn't occur in other cases at all. Actually, I wanted to ask if you all maybe called different demo nodes since we have multiple demo versions.

So, inconsistently reading the configuration lead to the problem but in principle the problem persists: Since `table_4` is suddenly being used but never mentioned before it results in a runtime error - unfortunately in a strange one. From my understanding, a correct fix would mean to agree on where the proper source of configuration is to be read from to instantiate all required UP objects at the beginning. Is it the parameter server? As discussed during the meeting, it can't be the symbolic fact generation because knowledge about all tables and locations needs to exist even for the first plan before the robot perceives much of the environment at all.

**Comment by alexander-sung** [comment] 2024-02-27 16:09
There's another thought I want to add to defend the current implementation. Improvements, also completely different solutions, are regardless very welcome. We saw a disadvantage of creating object representation instances on demand. Thus, while working with the list of UP objects, suddenly a new object appears.

What is your take on specifying the goal of the planning problem, e.g., target object on target table, in the starting script statically? No config file, no parameter server is read since nothing is executed, so where is `table_4` coming from? @sebastianstock introduced a nice mechanism for the last demo by simply using strings, which I personally never used with UP before. It's indeed valid and also quite common regardless of UP - but also then: errors would be runtime errors. There's simply no type checking happening before execution, so while I'm open to changing to this method consistently, we should have a lot more tests first.

**Comment by mintar** [comment] 2024-02-28 10:14
Since this is a planning question, I'd like to hear @sebastianstock's and/or @marcvinci's input on this.

**Comment by sebastianstock** [comment] 2024-02-28 13:18
I agree that the general problem is that we need just one source of information about objects in the demo. 
Currently, some information comes from the parameters server and the fact generator,  but the domain also seems to contain much hand-coded information. 

This particular issue is caused by the mix of information from the parameter server, i.e., `'base_table_4_pose'`, and the hand coded information that there are only three tables ('table_1', 'table_2', 'table_3'), which than leads to the error by creating a new `'table_4'` when updating the `at` fluent.

https://github.com/DFKI-NI/mobipick_labs/blob/ebc06d97520c94b594ee5aa49eeff223c6bf9cc6/tables_demo_planning/src/tables_demo_planning/tables_demo_api.py#L44-L46
 
Therefore, this particular issue could be fixed by creating the table objects based on the` base_table_X_pose `poses.

But there is still the question where to get all the information about objects from:
In my opinion the environment representation (for us currently the fact generator) should maintain the robot's current view of the world and should therefore be queried by the planner and other ROS nodes for that.
If there are objects of which we initially known they exist but we don't know their pose, this should be stored in the environment representation as well. And if completely new objects appear, which the planner was not ware of initially, then those should just be added to the planning problem once we do re-planning.

**Comment by marcvinci** [comment] 2024-02-28 13:50
I was about to comment the same regarding how  to fix this current problem. The tables and poses are assumed to be static and specified in config files loaded into the parameter server, so in the code snippet send by Sebastian, we should also create the table objects using the parameter server, as we do with the poses.

I also agree with Sebastian, that everything that is dynamic (e.g. objects, robot pose, arm pose), should be coming from the fact generator or the environment representation, which is currently the case, so for now I don't think we need to change anything there.

**Comment by alexander-sung** [comment] 2024-02-28 17:05
I very welcome your proposal, @sebastianstock. This indeed sounds like a step further to the environment representation we are aiming for since a while ago. It would then serve as the single source of information about everything the robots know about the environment, no matter how and when it was acquired. So, static information needs to go there, read from configuration on start-up. Dynamic information goes there, acquired from symbolic fact generation. Right? Architecture-wise it's also nice that the environment representation is the interface to access for current information. Thus, the text-based test can fill in knowledge into the environment representation completely without any ROS node.

**Comment by mintar** [comment] 2024-02-29 14:29
Do you plan on fixing this until the demo next Wednesday/Thursday? Currently I'm working around this bug by removing `base_table_4_pose` from `cic_tables_demo.yaml`, but it would be nice to fix this properly.

**Comment by alexander-sung** [comment] 2024-02-29 14:58
How is properly from your point of view? The environment representation as single source of information won't be ready next week.

I wanted to check back after the ChargePal workshop with you whether you prefer adding table 4 to planning or removing it from the configuration - both as very simple workarounds, for sure.

**Comment by mintar** [comment] 2024-02-29 15:24
I think there are multiple things that are definitely bugs no matter how you look at it, so they could be already fixed now:

1. Instead of hardcoded `("table_1", "table_2", "table_3")`, the values should be read from the parameter server, as Sebastian suggested.
2. One should never iterate over an iterable (`self.objects`) while calling functions inside the iteration that can change the iterable (`self.get()`).

Regarding (2): What exactly does `self.objects` represent? The set of objects known to the planner, or the set of currently cached objects (i.e., objects which already have a UP object created for them)? I believe this is the root of the bug. We want to iterate over the set of known objects and create UP objects for them. What the current implementation does (I think) is that it iterates over the set of UP objects and creates UP objects, but while doing so it somehow accidentally discovers more UP objects and adds them to the set of UP objects, thereby causing the bug.

These are small fixes that could be done right now without having to wait for a big thing to be implemented.

**Comment by alexander-sung** [comment] 2024-02-29 16:36
1. Parameter server is what I suggested for this reason in the first place. The planner needs to be sure that the information will be provided from there. Since we agree here, I'll take care of this.
2. This is a valid point and I shall make this more robust. At this point, however, since an inconsistency appeared, the planner can only make further assumptions or explicitly throw an exception rather than letting an unexpected error occur. The later would indeed be an improvement, I agree.

Let's just keep in mind that the up-esb is just a module which can be used properly or not. The whole dynamic creation of UP object instances was requested and quickly implemented for our last demo but we still need a consistent system description which component provides which information and when. Ideally, this specification comes from one (or all!) of our projects using both planning and Mobipick. As discussed, the instance-on-demand-creation is a brittle construct, but again: how to deal with unspecified information coming from future implementations? For next time, I propose to wait for the proper interfaces before planning with them. With a sound environment representation, we can also get rid of this construct.

As for `self.objects`, I again recommend an IDE which reveals the code documentation easily. You're free to say, of course, that the description is insufficient. `self.objects` are all currently created UP objects, and yes, it's the root of the bug, that's right. Before starting the loop, there was no UP object corresponding to Location for table_4 but it is requested to be assigned, since a `base_table_4_pose` has been specified.

**Comment by alexander-sung** [comment] 2024-03-01 10:15
Tested in simulation so far.

**Closed as completed** 2024-03-11 15:35 UTC
Labels: bug
